apiVersion: v1
kind: ConfigMap
metadata:
  name: bff-db-runtime
  labels:
    app.kubernetes.io/name: bff
    app.kubernetes.io/part-of: arbeidsflate
data:
  DB_HOST: bff.postgres.database.azure.com
  DB_PORT: "5432"
  DB_NAME: arbeidsflate-at23-bff
  DB_USER: bff
