apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
spec:
  template:
    spec:
      containers:
        - name: bff
          env:
            - name: OTEL_TRACES_SAMPLER_ARG
              value: "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bff-runtime
  labels:
    app.kubernetes.io/instance: at23
data:
  HOSTNAME: https://af.at23.altinn.cloud
  OIDC_URL: test.idporten.no
  OIDC_PLATFORM_URL: platform.at23.altinn.cloud/authentication/api/v1/openid
  DIALOGPORTEN_URL: http://graphql.product-dialogporten.svc.cluster.local
  ENABLE_GRAPHIQL: "true"
  PLATFORM_BASEURL: https://platform.at23.altinn.cloud
  AUTH_CONTEXT_COOKIE_DOMAIN: .at23.altinn.cloud
  ALTINN2_BASE_URL: https://at23.altinn.cloud
