apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-runtime
  labels:
    app.kubernetes.io/instance: prod
data:
  DIALOGPORTEN_STREAM_URL: https://altinn-prod-api.azure-api.net/dialogporten/graphql/stream
