apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: arbeidsflate-azure-kv
  namespace: product-arbeidsflate
spec:
  provider:
    azurekv:
      vaultUrl: https://dp-fe-staging-kv-scu3ld5.vault.azure.net/
