apiVersion: storage.dis.altinn.cloud/v1alpha1
kind: Database
metadata:
  name: bff
spec:
  serverType: dev
  storage:
    sizeGB: 32
    tier: Burstable_Standard_B2ms
  highAvailabilityEnabled: false
  backupRetentionDays: 14
