apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
spec:
  template:
    spec:
      containers:
        - name: bff
          env:
            - name: DB_USE_AAD_AUTH
              value: "true"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: bff-bff-dis-pgsql
                  key: host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: bff-bff-dis-pgsql
                  key: port
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: bff-bff-dis-pgsql
                  key: dbname
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: bff-bff-dis-pgsql
                  key: user
