apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
spec:
  template:
    spec:
      containers:
        - name: bff
          env:
            - name: OTEL_TRACES_SAMPLER_ARG
              value: "0.05"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bff-runtime
  labels:
    app.kubernetes.io/instance: prod
data:
  HOSTNAME: https://af.altinn.no
  OIDC_URL: idporten.no
  OIDC_PLATFORM_URL: platform.altinn.no/authentication/api/v1/openid
  DIALOGPORTEN_URL: https://altinn-prod-api.azure-api.net/dialogporten
  ENABLE_GRAPHIQL: "false"
  PLATFORM_BASEURL: https://platform.altinn.no
  AUTH_CONTEXT_COOKIE_DOMAIN: .altinn.no
  ALTINN2_BASE_URL: https://altinn.no
