apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: arbeidsflate-azure-kv
  namespace: product-arbeidsflate
  labels:
    app.kubernetes.io/part-of: arbeidsflate
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: ${ARBEIDSFLATE_KEY_VAULT_URL}
      serviceAccountRef:
        name: arbeidsflate-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: arbeidsflate-secrets
  labels:
    app.kubernetes.io/part-of: arbeidsflate
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: arbeidsflate-azure-kv
  target:
    name: arbeidsflate-secrets
    creationPolicy: Owner
  data:
    - secretKey: databaseConnectionString
      remoteRef:
        key: databaseConnectionString
    - secretKey: redisConnectionString
      remoteRef:
        key: redisConnectionString
    - secretKey: idPortenSessionSecret
      remoteRef:
        key: idPortenSessionSecret
