apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-runtime
  labels:
    app.kubernetes.io/instance: at23
data:
  DIALOGPORTEN_STREAM_URL: https://discore-at23-m22d0r-apim.azure-api.net/dialogporten/graphql/stream
