apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../apim/base
patches:
  - target:
      kind: Backend
      name: arbeidsflate-frontend
    patch: |
      - op: replace
        path: /spec/url
        value: https://arbeidsflate.prod.dis-core.altinn.cloud
  - target:
      kind: Api
      name: arbeidsflate-frontend
    patch: |
      - op: replace
        path: /spec/versions/0/serviceUrl
        value: https://arbeidsflate.prod.dis-core.altinn.cloud
  - target:
      kind: Backend
      name: arbeidsflate-bff
    patch: |
      - op: replace
        path: /spec/url
        value: https://arbeidsflate.prod.dis-core.altinn.cloud/api
  - target:
      kind: Api
      name: arbeidsflate-bff
    patch: |
      - op: replace
        path: /spec/versions/0/serviceUrl
        value: https://arbeidsflate.prod.dis-core.altinn.cloud/api
