apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: product-arbeidsflate
resources:
  - ../../common/base
  - apps
  - jobs
  - ../../databases/bff/overlays/at23
patches:
  - path: secretstore-vault-url.yaml
images:
  - name: ghcr.io/altinn/dialogporten-frontend-frontend
    newTag: set-by-ci
  - name: ghcr.io/altinn/dialogporten-frontend-node-bff
    newTag: set-by-ci
