apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: arbeidsflate-azure-kv
  namespace: product-arbeidsflate
spec:
  provider:
    azurekv:
      vaultUrl: https://dp-fe-test-kv-nyzv2d7xhs.vault.azure.net/
