apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: arbeidsflate-azure-kv
  namespace: product-arbeidsflate
spec:
  provider:
    azurekv:
      vaultUrl: https://dp-fe-yt01-kv-ptr4s4f4v4.vault.azure.net/
