apiVersion: storage.dis.altinn.cloud/v1alpha1
kind: Database
metadata:
  name: bff
  labels:
    app.kubernetes.io/name: bff
    app.kubernetes.io/part-of: arbeidsflate
spec:
  name: bff
  server:
    name: bff
  access:
    principals:
      - role: Owner
        identityRef:
          name: bff
  deletionPolicy: Retain
