apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - database.yaml
  - logical-database.yaml
  - application-identities.yaml
commonLabels:
  app.kubernetes.io/part-of: arbeidsflate
