apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: arbeidsflate-azure-kv
  namespace: product-arbeidsflate
spec:
  provider:
    azurekv:
      vaultUrl: https://dp-fe-prod-kv-bkd4b2x72l.vault.azure.net/
